environment:
  GOPATH: c:\projects

services:
  - postgresql

install:
  - set PATH=%GOPATH%\bin;%PATH%
  - cd %APPVEYOR_BUILD_FOLDER%
  - go env
  - go version
  - go get github.com/tools/godep
  - godep get github.com/mitchellh/gox
  - godep get github.com/jteeuwen/go-bindata/...
  - godep restore

build_script:
  - godep go build

test_script:
  - godep go test

deploy: off